### ISSUE TITLE
android-native compilation fails

### ISSUE THREAD

**Issue by romamik** [Kode/Kore#113]
Unresolved symbols in OpenGL.cpp: glGenQueries, glBeginQuery etc.
I think this is because by default target android api is android-15 and these function are defined in OpenGL ES 3.0, which is supported only in android-18+.

**Comment by RobDangerous** [comment]
Time for more #ifdefs

**Comment by romamik** [comment]
https://github.com/KTXSoftware/Kore/pull/114

**Comment by RobDangerous** [comment]
Merged, thanks.
