### ISSUE TITLE
max command not supported

### ISSUE THREAD

**Issue by TimBo93** [Kode/Kore#122]
`	float t = max(1,0);
`

results in

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		2 compilation errors.  No code generated.	Exercise5	C:\Users\tborowski\Desktop\tmp\Exercise5\build\CUSTOMBUILD	1	
> Error		0:39: 'max' : no matching overloaded function found	Exercise5	C:\Users\tborowski\Desktop\tmp\Exercise5\build\CUSTOMBUILD	1	
> Error		0:39: '' :  syntax error	Exercise5	C:\Users\tborowski\Desktop\tmp\Exercise5\build\CUSTOMBUILD	1	
>

**Comment by SpookyFM** [comment]
Try max(1.0, 0.0). From my understanding, the GLSL version that Kore targets doesn't have a max for integer, and the variable isn't automatically casted.

**Comment by RobDangerous** [comment]
Aye, that error message is correct (same thing happens on shadertoy for example). "no matching overloaded function" -> there is no function of that name and the passed argument types.

**Comment by TimBo93** [comment]
you are absolutely right.
