### ISSUE TITLE
Windows Direct3D 9 context loss

### ISSUE THREAD

**Issue by romamik** [Kode/Kore#130]
On my machine when I run project, lock machine and unlock it back, game keeps updating, but rendering do not work. This is for Direct3D 9 and simple kha project on Windows 10. Also tested with Direct3D 11 and OpenGL and there was no such problem.

**Comment by RobDangerous** [comment]
Context loss is a complicated situation which can not be resolved by a framework on its own because all gpu data is invalid when it happens. Because it's a D3D9 and very old Android only problem I currently do not plan to handle it (like many D3D9 apps).

**Comment by romamik** [comment]
I did not know that DirectX11+ can't loose context. That's what I found about this: https://msdn.microsoft.com/en-us/library/windows/apps/dn458383.aspx To be honest context loss is still possible, but in such conditions that one cannot expect app to survive. 
But what about OpenGL? I can't find any reliable information on which devices/operating systems context loss is possible or not. I heard somewhere (in Starling documentation?) that on iOS and (maybe) OS X context is never lost. And I never heard something like this about Android and Windows. I do believe you, I myself do not have any real experience with native OpenGL programming, but I'm really curious is it official or it just don't loose context but don't guarantee that?

May be we can throw an error or shut down application when context is lost. I understand that proper handling of context loss is a big task that may be really do not worth it.

**Comment by RobDangerous** [comment]
The concept of a context loss just doesn't exist in OpenGL, that's why it's hard to find any information about it. Android adds an api for that itself but I've never actually seen it happen.
Proper error on context loss - yes, we should do that.

**Comment by RobDangerous** [comment]
Graphics::swapBuffers now returns false when the context was lost.
