### ISSUE TITLE
Direct3D11 empty scene

### ISSUE THREAD

**Issue by TimBo93** [Kode/Kore#137]
this
`node Kore/make -g direct3d11 -v vs2015`
results in
<img width="459" alt="d3d11vs15" src="https://cloud.githubusercontent.com/assets/8701341/21957664/dc65b55e-da9b-11e6-92e9-3f14f9e4c6c0.PNG">

OpenGL works as expected
`node Kore/make -g opengl -v vs2015`
![image](https://cloud.githubusercontent.com/assets/8701341/21957678/27022f02-da9c-11e6-9f17-3071939a6282.png)

**Comment by TimBo93** [comment]
could also be interesting:
```
D3D11 ERROR: ID3D11DeviceContext::ClearDepthStencilView: The Depth Value passed (1000.000000), is outside the valid range of 0.0f to 1.0f. [ EXECUTION ERROR #263: CLEARDEPTHSTENCILVIEW_INVALID]
D3D11 ERROR: ID3D11DeviceContext::ClearDepthStencilView: The Depth Value passed (1000.000000), is outside the valid range of 0.0f to 1.0f. [ EXECUTION ERROR #263: CLEARDEPTHSTENCILVIEW_INVALID]
D3D11 ERROR: ID3D11DeviceContext::ClearDepthStencilView: The Depth Value passed (1000.000000), is outside the valid range of 0.0f to 1.0f. [ EXECUTION ERROR #263: CLEARDEPTHSTENCILVIEW_INVALID]
D3D11 ERROR: ID3D11DeviceContext::ClearDepthStencilView: The Depth Value passed (1000.000000), is outside the valid range of 0.0f to 1.0f. [ EXECUTION ERROR #263: CLEARDEPTHSTENCILVIEW_INVALID]

```

**Comment by SpookyFM** [comment]
It looks like this is not a Kore bug but a "Game Technology" bug instead. I fixed that depth clear for all current exercises.
