### ISSUE TITLE
[Android] Screen size question

### ISSUE THREAD

**Issue by juakob** [Kode/Kore#159]
When you open an app in android it shows the bottom bar
![](http://cdn.redmondpie.com/wp-content/uploads/2016/03/Android-Google-design-guidelines-bottom-bar.jpg)

With the current implementation if you call System.windowWidth() or System.windowHeight() at the start of the app and the bar is still showing, it will substract to the resolution the bottom bar area. 

I made another implementation that just returns the full screen resolution of the phone, but dont know if its more a hack than a solution.  
#157 
#158

**Comment by RobDangerous** [comment]
The bar can be enabled via the korefile/khafile (project.targetOptions.android.disableStickyImmersiveMode), we have to factor that in as well.

**Comment by sh-dave** [comment]
Not a 100% sure on this, but maybe this is a better place for the code:
https://github.com/Kode/Kore/blob/master/Backends/Android/Sources/Kore/Display.cpp

With System.windowWidth/Height() you would then keep to get the size of the screen with factored in bottom bar like it is now?

**Comment by juakob** [comment]
We could add an if and ask if we are in immersive mode, if we are return the full screen width/height. If we are not return somthing similar to this https://github.com/Kode/Kha/blob/bbbb3bd150b5d2bdc8a1c5981a2d75ebc756f58d/Backends/Android/kha/SystemImpl.hx#L21

I agree that its more logical to have it in Display.cpp, but I'm not sure if it's logical for the end user to use Display. I think most users will think that if you call System.windowWidth/Height() and if you are in immersive mode you are going to get the full resolution.

Another problem is that if you run the app from android studio it dosent happen because it's a little slower and android has time to hide the bar, so the problem only shows if you are running it directly from the phone.
