### ISSUE TITLE
Title doubled on linux

### ISSUE THREAD

**Issue by ghost** [Kode/Kore#160]
If the title `Test` is passed to `System.init` in the window options, the window will have a title `TestTest`. The supplied title is being doubled.

![screenshot_20170311_150846](https://cloud.githubusercontent.com/assets/15932100/23827642/a395ea9e-066c-11e7-8520-e0b036559805.png)

To reproduce:

`Main.hx`:
```
package;

import kha.System;

class Main {
	public static function main() {
		System.init({title: "Test", width: 1024, height: 768}, function () {
			new Project();
		});
	}
}
```

`Project.hx`:
```
package;

import kha.Framebuffer;
import kha.Scheduler;
import kha.System;

import kha.Color;

class Project {
	public function new() {
		System.notifyOnRender(render);
		Scheduler.addTimeTask(update, 0, 1 / 60);
	}

	function update(): Void {
		
	}

	function render(framebuffer: Framebuffer): Void {
		var g = framebuffer.g2;
		g.begin(true, Color.Cyan);
		g.color = Color.Purple;
		g.fillRect(20, 20, 400, 400);
		g.end();
	}
}
```

**Comment by ghost** [comment]
thanks!
Is there a way I can easily update my Kore in Kode Studio?

**Comment by sh-dave** [comment]
You don't have to use the KS bundled Kha version, but can just clone the Kha repository someplace else.
Then in KS open File -> Preferences -> User/Workspace settings and add a path entry like so:
```
{
...
"kha.khaPath": "d:/projects/kode/Kha"
}
```

Kha path resolution order should be like:
- Kha folder in your project (f.ex. when you add Kha as git submodule)
- "kha.khaPath" in your KS settings
- default Kha bundled with KS

To get the latest Kha, check the last paragraph (Updateing Kha) here: https://github.com/Kode/Kha/wiki/Getting-Started
