### ISSUE TITLE
Display not found on linux

### ISSUE THREAD

**Issue by memilian** [Kode/Kore#169]
Updated to latest Kha/Kore, I get a crash at startup with the message :  "No display attached?"
```
Program received signal SIGSEGV, Segmentation fault.
At /home/memilian/dev/lib/Kha/Kore/Backends/System/Linux/Sources/Kore/System.cpp:186

**Comment by OvermindDL1** [comment]
How were you running it?  Was your `$DISPLAY` set?

**Comment by memilian** [comment]
yes $DISPLAY is set to ":0", it happens both running from the terminal or with Code::Blocks

**Comment by RobDangerous** [comment]
Please reopen if this didn't fix it.

**Comment by memilian** [comment]
fixed, thanks :)
