### ISSUE TITLE
[macos] Video playback doesn't loop / eventually crashes

### ISSUE THREAD

**Issue by nateupstairs** [Kode/Kore#186]
Videos played back with video.play(true) on macos result in this error repeatedly:

AVD error: Perf capability check failed: 0xe00002be

Which eventually compounds and crashes out the execution. It happens at the very moment the video reaches the end and doesn't loop properly.

**Comment by RobDangerous** [comment]
That is weird, for me they just don't loop at all. Also I don't see any code for looping. Are you sure you are talking about the macOS backend?

**Comment by nateupstairs** [comment]
Well, they don't loop, but they also error out at the end of playback even if i put video.play(false). This is on the osx backend [build -> macOS from Kode Studio]. I can give you my files if you want to test on them. I also pulled your newest kore from a couple hours ago and it's still happening.
