### ISSUE TITLE
Graphics2::fillTriangle does not draw when images or Text is also rendered

### ISSUE THREAD

**Issue by patternspandemic** [Kode/Kore#222]
A [gist example](https://gist.github.com/patternspandemic/2639840da4bc882aa57a77528efe82ec) of the issue.

Seems to be a problem somewhere within ColoredShaderPainter ::drawTriBuffer and ::drawBuffer.

**Comment by RobDangerous** [comment]
Can't reproduce on Windows using standard settings. Does this still happen? On what system?

**Comment by patternspandemic** [comment]
Thanks for taking a look. I'm on Linux. I'll try again with most recent Kore sometime today..

**Comment by patternspandemic** [comment]
Just tried with master (1a5523f68705ead30774828dcc0e9729fb0c4be9), unfortunately I get the same result.

**Comment by RobDangerous** [comment]
Aha, OpenGL thing. Fixed.

**Comment by patternspandemic** [comment]
Hi Robert, sorry to say the issue remains for me. Were you able to reproduce? Did this change the behavior noted in my Gist?

Thanks, Brad
