### ISSUE TITLE
[featurerequest] some graphic options and fixes

### ISSUE THREAD

**Issue by malublu** [Kode/Kore#239]
currently i look myself to implement this feautures in kore (but i don't know if i can it):

- change vsync option at runtime (*0)
- fix vsync for some graphic targets
    - d3d9
    - d3d12
    - Metal?
    - Vulkan?
- change antialiasingSamples option at runtime
- fix antialiasingSamples for some graphic targets
    - Vulkan?
    - Metal?
    - d3d12
- fix mouse lock/hide for some system target (*1)
    - linux
    - mac
    - more ...?
- requestBorderless (*1) (fullscreen not supported for some targets)
- exitBorderless (*1) (fullscreen not supported for some targets)
- requestMostTop (*1)
- exitMostTop (*1)
- resize/set position for the window (*1) (changeResolution needed?)
- replace changeResolution with resize/set postion?
- remove fullscreen or we need it? (can be replaced via mix of resize/set pos + requtestBorderless + requestMostTop)

do we need more?

(*0) nearly  finished for opengl and (*1) + android/ios, als no tests for ios
(*1) nearly finished for win/linux/mac, not tested for linux/mac and i can't make a test for mac.
       And i have also no idea if the code can work for the mac.

**Comment by RblSb** [comment]
@malublu you can just send PR, and we'll help you test

**Comment by RobDangerous** [comment]
What does fix vsync mean?

**Comment by malublu** [comment]
Not all targets implement it.
But currently, i have currently no time to work on it, because my "place of work" say no!
If i have private more time, i try to work on the code.

I also can send you my current work, if you want.

**Comment by grayhaze** [comment]
What's the status on this? Did @malublu ever share his WIP? I can't see any branches on his fork of Kore which would tie up with the description above.

**Comment by RobDangerous** [comment]
Don't think so. Working on window things myself right this minute.

**Comment by malublu** [comment]
@grayhaze it was a local copy. Currently i have no time to work on it. (Because my work)
I think it will take several months until I have time again.
But some other peoples work also on it. https://github.com/armory3d/armory/issues/224
If I find the code again, I can gladly upload it the next few days (weeks).

**Comment by RobDangerous** [comment]
All of this is now implemented in Kore for Windows via Direct3D 11 and OpenGL. Not yet fully exposed in Kha. Sorry @malublu, had to get cracking on it.

**Comment by malublu** [comment]
No Problem. @RobDangerous thanks for it 👍

**Comment by RobDangerous** [comment]
In theory the new Window API is now fully operational in Windows and mostly operational in macOS. Feel free to do some testing.

**Comment by RobDangerous** [comment]
If you still need something here, please open more specific issues.
