### ISSUE TITLE
matrices dont get transpose when set using setFloats directX 11

### ISSUE THREAD

**Issue by juakob** [Kode/Kore#250]
matrices dont get transpose when set using setFloats directX 11

**Comment by RobDangerous** [comment]
Fixed.

**Comment by juakob** [comment]
Wow that was fast!

**Comment by RobDangerous** [comment]
That's your fault, the way you prepare those issue reports makes it easy for me.

**Comment by juakob** [comment]
Well thats because I asume the error is always on my side, and only create an issues if I'm 99% sure that it's not on my side
