### ISSUE TITLE
vulkan build failed for linux

### ISSUE THREAD

**Issue by wicast** [Kode/Kore#272]
Here is the log, my pc setup is archlinux, gcc 8.1.1+20180531-1.

by the way, android seems have the same problem with clang, ndk r17.

`g++  -O2 -I./ -I../Sources/include -I../../../Kha/Backends/Kore/khacpp/include -I../../../Kha/Backends/Kore/khacpp/project/thirdparty/pcre-7.8 -I../../../Kha/Backends/Kore/khacpp/project/thirdparty/zlib-1.2.3 -I../../../Kha/Backends/Kore/khacpp/project/libs/nekoapi -I../../../Kha/Backends/Kore/khacpp/project/thirdparty/mbedtls-2.2.1/include -I../../../Kha/Kore/Sources -I../../../Kha/Kore/Backends/System/Linux/Sources -I../../../Kha/Kore/Backends/System/POSIX/Sources -I../../../Kha/Kore/Backends/Graphics5/Vulkan/Sources -I../../../Kha/Kore/Backends/Graphics4/G4onG5/Sources -I../../../Kha/Kore/Backends/Audio3/A3onA2/Sources  -DKORE_MULTITHREADED_AUDIO -DHX_LINUX -DHXCPP_API_LEVEL=330 -DSTATIC_LINK -DPCRE_STATIC -DHXCPP_SET_PROP -DHXCPP_VISIT_ALLOCS -DKORE -DROTATE90 -DKORE_G1 -DKORE_G2 -DKORE_G3 -DKORE_A1 -DKORE_A2 -DKORE_LINUX -DKORE_VULKAN -DVK_USE_PLATFORM_XCB_KHR -DKORE_POSIX -DKORE_G4 -DKORE_G5 -DKORE_G4ONG5 -DKORE_A3  -c ../../../Kha/Kore/Backends/Graphics4/G4onG5/Sources/Kore/G4.cpp -o g4.o -static-libgcc -static-libstdc++ -pthread -lasound -ldl -lvulkan -lxcb
In file included from ../../../Kha/Kore/Backends/Graphics5/Vulkan/Sources/Kore/CommandList5Impl.h:3,
                 from ../../../Kha/Kore/Sources/Kore/Graphics5/CommandList.h:3,
                 from ../../../Kha/Kore/Backends/Graphics4/G4onG5/Sources/Kore/G4.cpp:10:
../../../Kha/Kore/Backends/Graphics5/Vulkan/Sources/Kore/vulkan_mini.h:3:28: error: conflicting declaration ‘typedef long long unsigned int uint64_t’
 typedef unsigned long long uint64_t;
                            ^~~~~~~~
In file included from /usr/include/stdint.h:37,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/8.1.1/include/stdint.h:9,
                 from ../../../Kha/Kore/Backends/Graphics5/Vulkan/Sources/vulkan/vk_platform.h:84,
                 from ../../../Kha/Kore/Backends/Graphics5/Vulkan/Sources/vulkan/vulkan.h:31,
                 from ../../../Kha/Kore/Backends/Graphics5/Vulkan/Sources/Kore/Texture5Impl.h:4,
                 from ../../../Kha/Kore/Sources/Kore/Graphics5/Texture.h:4,
                 from ../../../Kha/Kore/Sources/Kore/Graphics5/Shader.h:3,
                 from ../../../Kha/Kore/Sources/Kore/Graphics5/Graphics.h:5,
                 from ../../../Kha/Kore/Backends/Graphics4/G4onG5/Sources/Kore/TextureImpl.h:4,
                 from ../../../Kha/Kore/Sources/Kore/Graphics4/Texture.h:4,
                 from ../../../Kha/Kore/Sources/Kore/Graphics4/Shader.h:3,
                 from ../../../Kha/Kore/Sources/Kore/Graphics4/Graphics.h:3,
                 from ../../../Kha/Kore/Backends/Graphics4/G4onG5/Sources/Kore/G4.h:3,
                 from ../../../Kha/Kore/Backends/Graphics4/G4onG5/Sources/Kore/G4.cpp:3:
/usr/include/bits/stdint-uintn.h:27:20: note: previous declaration as ‘typedef __uint64_t uint64_t’
 typedef __uint64_t uint64_t;
                    ^~~~~~~~
`

**Comment by RobDangerous** [comment]
Aye, Vulkan and Metal need some updating after the API changed for the console targets. Working on Metal right now, then Vulkan.

**Comment by wicast** [comment]
Do you consider [MoltenVK](https://moltengl.com/moltenvk/)?
This might save some time.

**Comment by RobDangerous** [comment]
I'm working with the MoltenVK author on SPIRVCross for a few years now but I won't put a second api abstraction in Kha. Saves some time at the start but takes more time in the long run when you're optimizing performance and fixing weird bugs.

**Comment by RobDangerous** [comment]
Metal is done, Vulkan compilation is fixed and it can render beautiful red triangles (aka not quite but almost usable).

**Comment by technicallyagd** [comment]
I also can't build with Vulkan backend targeting Linux, but for different reason. The current problem seems to be https://github.com/Kode/Kore/blob/e38cdfaee2efceda724eb9315e42734e50c7c988/Backends/System/Linux/Sources/Kore/System.cpp#L835
Since the namespace `windowimpl` is only declared if we are using OpenGL, calling `Kore::Window::get` in `Kore::System::init` will cause the build to fail. Hope this extra info helps.

**Comment by RobDangerous** [comment]
All fixed and in CI now, so it'll stay fixed.
