### ISSUE TITLE
Add start/count parameters to VertexBuffer->unlock()

### ISSUE THREAD

**Issue by johngirvin** [Kode/Kore#274]
In the current implementation, buffer size (via start and count) is specified at VertexBuffer->lock() time. In certain situations these values cannot be determined in advance and the whole buffer must be "locked". This results in VertexBuffer->unlock() submitting the whole buffer to the back end.

This issue is to investigate if it is possible, for a performance optimisation, to extend unlock() to accept size and count parameters and so perform partial submits of the buffer data.

**Comment by RobDangerous** [comment]
Hey, that was fixed a while ago.
