### ISSUE TITLE
[android-native] error 1281 after glDisableVertextAttribArray()

### ISSUE THREAD

**Issue by sh-dave** [Kode/Kore#287]
I guess this is the same as #31 

https://github.com/Kode/Kore/blob/8f9a3ae7e54d1dd936a1c351cbf5efab10d39458/Backends/Graphics4/OpenGL/Sources/Kore/VertexBufferImpl.cpp#L205-L208

I could fix it by using the following code, but i'm not sure where to best place the `glGet` call, so it's not called everytime `setVertexAttributes` runs as i guess once at startup somewhere would be enough?

```cpp
int maxVertexAttribArrays = 0;
glGetIntegerv(GL_MAX_VERTEX_ATTRIBS, &maxVertexAttribArrays);

for (int index = actualIndex; index < maxVertexAttribArrays; ++index)
...
```

**Comment by RobDangerous** [comment]
Finally a repro! OK, having a closer look tonight.

**Comment by sh-dave** [comment]
Fyi: easy to reproduce with [lubos tutorial 8](https://github.com/luboslenco/kha3d_examples/tree/master/tutorial08) and latest Kha

- `Samsung SM-G350` running `Android 4.2.2, API 17`

**Comment by RobDangerous** [comment]
Did exactly as you said, thanks!
