### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [Kode/Kore#299]
Would you like to [wrap any pointer data members](https://github.com/Kode/Kore/blob/5527e55e9fc4cf4594953c1ed1981c77c8db5669/Sources/Kore/Network/Connection.cpp#L20 "Update candidate: Connection class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by RobDangerous** [comment]
Nope.

**Comment by elfring** [comment]
I suggest to [reconsider the resource management in affected source files](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "C++ core guideline “R.11: Avoid calling new and delete explicitly”") once more.

**Comment by sh-dave** [comment]
Read the note again, that section specifically talks about `application code`, and not `resource management`.

**Comment by RobDangerous** [comment]
Stop being silly, guys.
