### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Kode/Kore#300]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [CBaseFilter::JoinFilterGraph](https://github.com/Kode/Kore/blob/4253a9a244bacf4eb80fc779c18a854088773a31/Backends/System/Windows/Libraries/DirectShow/BaseClasses/amfilter.cpp#L769 "CBaseFilter::JoinFilterGraph")
- [OGLTemplateApp::OnAppTerminating](https://github.com/Kode/Kore/blob/13ca9ace6f2d04eb59aa81574dc9fb8c97fb27c2/Backends/System/Tizen/Sources/Kore/OGLTemplate.cpp#L84 "OGLTemplateApp::OnAppTerminating function")
- [ShaderImpl](https://github.com/Kode/Kore/blob/1ed14124edd9d46a8ce061fbcd37e3cccf3e5395/Backends/Graphics4/OpenGL/Sources/Kore/ShaderImpl.cpp#L24 "Destructor for ShaderImpl")

**Comment by RobDangerous** [comment]
Dude, the first one is third party library code.
Second one is outdated Tizen code.
Third one doesn't even do a null pointer check.
Are you a bot?

**Comment by elfring** [comment]
There might be more [update candidates to consider](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDeleteShader.xhtml "Description for glDeleteShader()"), aren't there?

**Comment by RobDangerous** [comment]
Definitely a bot.
