### ISSUE TITLE
iOS: duplicate symbols from Kore::Display

### ISSUE THREAD

**Issue by johngirvin** [Kode/Kore#301]
Backends/System/iOS/Sources/Kore/Display.cpp
Backends/System/iOS/Sources/Kore/Display_2.cpp

These cause duplicate symbol errors when linking an iOS project. It seems to work if you comment out the stub methods in Display.cpp, but I wanted to check what the story was with these two files first to be sure.

**Comment by RobDangerous** [comment]
The Display API was recently reworked (and the Window API added), unfinished backend cleanup.

**Comment by johngirvin** [comment]
Is the fix to just replace Display.cpp with Display_2.cpp ?

**Comment by RobDangerous** [comment]
Probably but will have a look tomorrow (and check in whatever the fix is).

**Comment by RobDangerous** [comment]
A little late but I fixed it. Can't test whether things are actually working though, the iPad at work is so old, it doesn't do Metal. Next vacation in two weeks though.
