### ISSUE TITLE
OpenGL multiple wglMakeCurrent calls on Windows

### ISSUE THREAD

**Issue by luboslenco** [Kode/Kore#307]
We can save some perf by reducing the `wglMakeCurrent()` calls here:
https://github.com/Kode/Kore/blob/master/Backends/Graphics4/OpenGL/Sources/Kore/OpenGL.cpp#L311

Robert mentions:
> Oh, no, that line should stay where it is. But the loop should go, there's only one context even with multiple windows now.

**Comment by RobDangerous** [comment]
Fixed it but the loop has to stay - there's of course contexts for every window but they are only ever used in the swapBuffers call.
