### ISSUE TITLE
Crash when resizing window on macOS using OpenGL

### ISSUE THREAD

**Issue by luboslenco** [Kode/Kore#309]
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[BasicOpenGLView resize:]: unrecognized selector sent to instance 0x7ff9c5e48530'
```

**Comment by RobDangerous** [comment]
But...but that worked fine for me.

**Comment by RobDangerous** [comment]
Here it is: https://github.com/Kode/Kore/blob/master/Backends/System/macOS/Sources/Kore/BasicOpenGLView.mm#L344
Did you maybe compile for OpenGL?

**Comment by luboslenco** [comment]
Yes - OpenGL. 😶

**Comment by RobDangerous** [comment]
I don't actively test that anymore but should be easy to fix...

**Comment by RobDangerous** [comment]
Fixed.
