### ISSUE TITLE
Crash when opening higher than display resolution window on macOS using OpenGL

### ISSUE THREAD

**Issue by luboslenco** [Kode/Kore#310]
OpenGL will not stop haunting me till I fully switch to metal. Will try to fix asap myself, just noting down. 😬

**Comment by RobDangerous** [comment]
On Windows we cap the window size because bigger than resolution windows are not supported by Windows.

**Comment by luboslenco** [comment]
Opening higher than display resolution window seems ok. Must be something different than I originally though, will open new issue once I discover it.
