### ISSUE TITLE
[linux] Key auto repeat

### ISSUE THREAD

**Issue by lordwelch** [Kode/Kore#327]
The Linux backend (and possibly others, anything that uses X11) needs to either set or add the option to set Detectable Auto Repeat that will fix the issue in Kode/Kha#820.

[Xlib documentation](https://www.x.org/releases/X11R7.7/doc/man/man3/XkbSetDetectableAutoRepeat.3.xhtml)

XCB does not have any documentation on it yet but [awesomeWM](https://github.com/awesomeWM/awesome/blob/master/xkb.c#L408) does this

```C
/* Enable detectable auto-repeat, but ignore failures */
xcb_discard_reply(globalconf.connection,
        xcb_xkb_per_client_flags(globalconf.connection,
                                 XCB_XKB_ID_USE_CORE_KBD,
                                 XCB_XKB_PER_CLIENT_FLAG_DETECTABLE_AUTO_REPEAT,
                                 XCB_XKB_PER_CLIENT_FLAG_DETECTABLE_AUTO_REPEAT,
                                 0,
                                 0,
                                 0)
        .sequence);
```

**Comment by Sanva** [comment]
@RobDangerous looks like this is fixed by now, isn't it? I do not see anything weird in Linux (using Linux Mint).

**Comment by RobDangerous** [comment]
Hm, looks like it, thanks.
