### ISSUE TITLE
D3D11 swap effect warning

### ISSUE THREAD

**Issue by luboslenco** [Kode/Kore#328]
> DXGI WARNING: IDXGIFactory::CreateSwapChain: Blt-model swap effects (DXGI_SWAP_EFFECT_DISCARD and DXGI_SWAP_EFFECT_SEQUENTIAL) are legacy swap effects that are predominantly superceded by their flip-model counterparts (DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL and DXGI_SWAP_EFFECT_FLIP_DISCARD). Please consider updating your application to leverage flip-model swap effects to benefit from modern presentation enhancements. More information is available at http://aka.ms/dxgiflipmodel.

https://github.com/Kode/Kore/blob/master/Backends/Graphics4/Direct3D11/Sources/Kore/Direct3D11.winrt.cpp#L222

Not sure if something prevents us from upgrading. Seems to run fine with the `DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL`, although I did not notice performance improvement.

**Comment by RobDangerous** [comment]
Let's change it then.

**Comment by RobDangerous** [comment]
Aha, I had actual reasons for not doing it. Not supported on Windows 7, see https://docs.microsoft.com/en-us/windows/desktop/api/dxgi/ne-dxgi-dxgi_swap_effect
Will do a version check then and hope for the best...

**Comment by RobDangerous** [comment]
And for reference, found this one in my bookmarks: https://blogs.msdn.microsoft.com/directx/2018/04/09/dxgi-flip-model/

**Comment by luboslenco** [comment]
Ah, of course.

Also, `DXGI_SWAP_EFFECT_FLIP_DISCARD` seems to be Windows 10 only according to https://docs.microsoft.com/en-us/windows/desktop/api/dxgi/ne-dxgi-dxgi_swap_effect?
While the `DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL` is Windows 8+. Which would mean we need to bump the check at https://github.com/Kode/Kore/commit/3c57df42d168a5df4a3bf8804b84296ea045f1a8.

**Comment by RobDangerous** [comment]
When you thing something would be simple...
Also have to look into msaa support.

**Comment by RobDangerous** [comment]
Windows 10 check returns false on my up to date Windows 10. More secrets to uncover...

**Comment by mirh** [comment]
Mhh just for the records, speaking of secrets, W7 should support flip sequential if you just install the platform update
https://github.com/mpv-player/mpv/pull/4273
