### ISSUE TITLE
Sync with Kha

### ISSUE THREAD

**Issue by RblSb** [Kode/Kore#340]
- [ ] Rewrite `findIndex` from [this](https://github.com/Kode/Kore/blob/master/Sources/Kore/Graphics2/Graphics.cpp#L736) to [this](https://github.com/Kode/Kha/blob/master/Sources/kha/graphics4/Graphics2.hx#L725) ([charBlocks implementation link](https://github.com/Kode/Kha/blob/master/Sources/kha/Kravur.hx#L146)).
- [x] Add `System.language` and link with Kha (can return "en" for start).
- [ ] Implement `System.language` and `System.vibrate`

Some Kode to Kha features to remember?

**Comment by RobDangerous** [comment]
I think language and vibrate is done and G2 will get a complete rewrite, so... looks like we are done here.
