### ISSUE TITLE
[linux] please add mouse lock - unlock support for Krom

### ISSUE THREAD

**Issue by trsh** [Kode/Kore#341]

**Comment by zicklag** [comment]
I am currently using mouse lock and unlock in Krom on linux with Armory. Is it not working at all for you?

**Comment by BlackGoku36** [comment]
It doesn't work for MacOS too
Lock no, hide no

**Comment by trsh** [comment]
@zicklag lock, yes, unlock no. Haven't checked in 0.6 yet.

**Comment by RobDangerous** [comment]
Not enough info. Please check in a current Kore revision.

**Comment by BlackGoku36** [comment]
Current kore revision?

**Comment by trsh** [comment]
@RobDangerous closing issues seems kind of trendy lately, but here is your example:

[ex.zip](https://github.com/Kode/Kore/files/2773278/ex.zip)

KHA and Kore just updated via:

git submodule foreach --recursive git pull origin master
git pull origin master

Kode studio khaPath set to it

Run in Krom-Linux, mouse cursor not locked
Run in HTML5-Linux, mouse is locked

Same problem with unlock.

Please re-open.

**Comment by RobDangerous** [comment]
When you run in Krom you don't use your updated Kore.

**Comment by trsh** [comment]
@RobDangerous so what can I do? KromPath? I will try, if its same, i gona explode in all directions!

"Debug adapter process has terminated unexpectedly (exit code: 1)"

AAAAAAAAAAAAAA!

**Comment by trsh** [comment]
@RobDangerous does the example really work for u, on latest Krom and Kore?

**Comment by zicklag** [comment]
@trsh Try Krom from here: https://github.com/armory3d/krom_bin.

I have unlock and lock working in Armory from Git with the latest of Kha, Krom, Kore and everything else. If I get time I'll try to send you my example.

**Comment by trsh** [comment]
@zicklag thank u. Will experiment.
