### ISSUE TITLE
Gamepad(use DirectInput) does not work

### ISSUE THREAD

**Issue by alnon** [Kode/Kore#343]
I'm using PS4 controller. However, after accepting axis input once, the reaction is gone.
Since "DirectInput8 / Pad0 / initialized" are displayed, I think that initialization has been successful.
I am using Windows, so I referred to the following place.
Kore/Backends/System/Windows/Sources/Kore/System.cpp

When using DirectInput, I think that the InputGetState variable will always be NULL.
Although it may be wrong, I confirmed that input can be obtained when the handleDirectInputPad function loops individually outside the if statement (I have not confirmed the value is correct).

**Comment by DarthVernus** [comment]
Take a look at this code:
`if (InputGetState != nullptr && (detectGamepad || gamepadFound))`
XInput pad works because gamepadFound is true:
```
if (dwResult == ERROR_SUCCESS) {
				gamepadFound = true;
```
DirectInput pad does not work, because gamepadFound will always be false.
You need to add gamepadFound = true to handleDirectInputPad.

**Comment by RobDangerous** [comment]
Good find, please send a pull request.

**Comment by RobDangerous** [comment]
W00t, nobody sent a pull request and now I have to dig up a dinput gamepad 😢
