### ISSUE TITLE
Dependency License Questions

### ISSUE THREAD

**Issue by zicklag** [Kode/Kore#348]
After doing a license scan I have a couple questions:

* In [Backends/System/Windows/Libraries/DirectShow/BaseClasses](https://github.com/Kode/Kore/tree/master/Backends/System/Windows/Libraries/DirectShow/BaseClasses) I cannot find any license, but there is a copyright by Microsoft in all of the files. Is there a missing license file?
* The Oculus SDK has a [notice](https://github.com/Kode/Kore/blob/master/Backends/System/Windows/Libraries/OculusSDK/THIRD_PARTY_NOTICES.txt#L310) about `librsync` being under the LGPL license. Will that not end up in Kore at runtime?

**Comment by RobDangerous** [comment]
The DirectShow thing is ok to be used in Windows, it's Microsoft sample code and librsync is nowhere to be found - maybe it's in some Oculus dll but then it's ok anyways.
