### ISSUE TITLE
[Feature Request]KoreMake create IOS and Android Visual Studio Projects.

### ISSUE THREAD

**Issue by Paolo-Oliverio** [Kode/Kore#355]
As Visual Studio supports both IOS and Android and feel way more natural for some windows users, i.e. for me, to use it instead of Apple or Android studio.

**Comment by RobDangerous** [comment]
I heard about Android Visual Studio things but not iOS. Tell me more about that please.

**Comment by Paolo-Oliverio** [comment]
For IOS it is included in the multiplatform components for visual studio and there are various template for it(multiplatform one and IOS only) targeting c++ preconfigured to use clang on both ios and android with support for multiple architectures.
On IOS there is also a third party commercial implementation that if I remember well was(several years ago) able to sign without a mac(while I never tested it).
For android both plain visual studio and nvidia Tegra nsight exists.
By reference you can easely find toolchains for cmake targeting nvidia solution while
microsoft modified its own fork of cmake to add visual studio multiplatform projects, but as far as I know it hasn't been merged in the main cmake repo.
You can also just install mobile multiplatform components in visual studio and create the multiplatform solution from the multiplatform(Android/IOS) opengles template to look at the generated project stucture.
Both 2015 and 2017 supports it and both nvidia and visual studio are very good for debugging(both on device and simulator) and feel more performant and streightforward than the provided gradle build system.
This may also unlock the possibility to create multiple projects targeting a good number of targets in a single vs solution.

**Comment by RobDangerous** [comment]
The iOS-thing in Visual Studio complains about not finding some remote-compilation-option - which I suppose means it can only work in combination with a Mac. Sorry, pull-requests welcome but I don't want to invest time in that myself.

**Comment by RobDangerous** [comment]
And for Android - the thing in Visual Studio seems super-basic with almost no options, the Tegra thing seems to have been discontinued a long time ago, and the Android Game Development Extension has a crazy license I can not comply with, requiring me to use it only for games or game engines (Kinc is neither). Nah, no fun.
