### ISSUE TITLE
[HTML5] Compilation error Missing windowsdata.h implementation in the html5 backend included from windows.h

### ISSUE THREAD

**Issue by Paolo-Oliverio** [Kode/Kore#356]
apart from this issue what's the state of the html5 backend?Can someone point me to a commit where it compiles?

**Comment by RobDangerous** [comment]
Haven't used it in a loooong time because I make browser things in Kha.

**Comment by Paolo-Oliverio** [comment]
I have a html5 only heavy modified kha (very light 5k gzipped super focused on vertical mobile 2d games) with  live coding and all.But i'm loosing interest in mobile so I need a native sideproject focused on bigger screens (especially desktop, smart tv and console) and willing to give hot realoaded c , multithreaded pipeline plus few interesting native libs a try.I understand that now kha js is lightyears better than the kore emscripten backend , but I really need some help with this last one.
Did it woked at some point or I need to fill the gaps from scratch?

**Comment by RobDangerous** [comment]
Yes, worked fine, just needs to be updated for the Kore API changes which happened meanwhile I think. Have a look at what happened to the other backends after the last commit to the HTML5 backends.

**Comment by Paolo-Oliverio** [comment]
I also noticed you used glfw for that backend and it should be a c wrapper around some js version of glfw if I remember well so I'm evaluating the possibility to replace glfw with handmade(or haxe/ts transpiled) js that fits naturally in the kore api e.g. inlining js directly in the html5 backend.

**Comment by Paolo-Oliverio** [comment]
Today I filled the spaces and now it compiles ,still with glfw I have to understand how much it weights against a minimal js game framework. I'll probably commit to my fork but it is all but production ready. As most functions are just empty.

**Comment by RobDangerous** [comment]
If I remember correctly this is not something like regular glfw at all but just a minimal thing to get things running by kripken himself.
That said, if you don't plan to commit back, no more support from me.

**Comment by Paolo-Oliverio** [comment]
I didn't mean that.it is just a temporary solution.when I got something better I'll send you everything. of course I can just make a pull request for your to see what I'm talking about.

**Comment by RobDangerous** [comment]
Okidoki! (Had people explain everything to them, then walk off without contributing back before so I became more careful to not waste my time)

**Comment by RobDangerous** [comment]
Hey, it compiles now.
