### ISSUE TITLE
[dx11] drawIndexedVertices resets pixel shader resources e.g. texture.

### ISSUE THREAD

**Issue by Paolo-Oliverio** [Kode/Kore#363]
Draw indexed vertices calls context->PSSetShaderResources(0, D3D11_COMMONSHADER_INPUT_RESOURCE_SLOT_COUNT, nullviews);
This resets some state I need preserved between calls and I don't understand why it makes this call in the first place.

**Comment by RobDangerous** [comment]
W00t, what's the reason for the weird, unreadable and super long title and all those question and exclamation marks? Please stop hitting your head on the keyboard.

**Comment by Paolo-Oliverio** [comment]
I was in a hurry and now on mobile I didn't understand how to change it. However I have a system that makes a variable number of calls with the exact same pipeline and different buffers.I had to modify it to take a reference to the texture to set it back at every call.I want to know the reason about that call and if I can remove it.I will try with other graphic APIs to check if they present the same behaviour.

**Comment by RobDangerous** [comment]
It's necessary so texture don't have to be nulled explicitely. Otherwise there was trouble when changing shaders but I don't remember the details.

**Comment by Paolo-Oliverio** [comment]
It is more than actual graphic APIs normally does so it got in my way while doing a port from raw gfx API where I manage state manually.I ended up removing it to maintain 1 to 1 consistency with my existing code.

**Comment by RobDangerous** [comment]
Well, that's not helpful.
