### ISSUE TITLE
Dx11 uint8 vertex Color format should be normalized.

### ISSUE THREAD

**Issue by Paolo-Oliverio** [Kode/Kore#364]
I see that graphic 2 uses 4 floats and not the provided Color format  uint8 vector so it goes around this issue.I still have to check what other APIs does but I guess that few more formats could be added.e.g. in my Html5 engine I use unsigned shorts for UV (kore support them signed) so I cannot port previous code  and assets 1to1 without modifying kore.

**Comment by RobDangerous** [comment]
Fixed.
