### ISSUE TITLE
VSync broken on macOS + OpenGL

### ISSUE THREAD

**Issue by luboslenco** [Kode/Kore#367]
On macOS 10.14 + OpenGL +  Xcode 10, enabling VSync no longer has effect:
https://github.com/Kode/Kore/blob/master/Backends/System/macOS/Sources/Kore/BasicOpenGLView.mm#L276

Xcode 9 does not have this issue. Kore already defaults to Metal but since OpenGL option is still there it might be handy to have this listed as a known issue.

**Comment by RobDangerous** [comment]
Yes, I heard that from some other project as well and I don't know whether we can do anything about it.

**Comment by RobDangerous** [comment]
Latest info from Andre: https://twitter.com/FlohOfWoe/status/1103296098834305026

**Comment by luboslenco** [comment]
Fixed on macOS 10.14.4 + Xcode 10.2.1.
