### ISSUE TITLE
Best approach for implementing per vertex color tris.

### ISSUE THREAD

**Issue by aleph1** [Kode/Kore#373]
I am interested in using Kore as part of the rendering layer for my engine, but I have a particular need for tris that are colored on a per vertex basis. Basically I have an extensive engine built in AIR that uses 2D meshes and this approach, and I think Kore would be capable of this as is, or with some minor modifications. Graphics 2 has this function:

void Graphics2::ColoredShaderPainter::setTriColors(float opacity, uint color)

But am I better to add an additional function to Graphics2, or to build a system on top of this that would me allow to do something like this:

setTriColorsPerVertex(float opacity1, uint color1, float opacity2, uint color2, float opacity3, uint color3 )

I am happy to work on planning/adding code to deal with per vertex colours, as it is something that seems to be used more as time goes on. I realize it might break compatibility with certain render targets. Any information would be appreciated in terms of this, and where I can find an overview of Graphics1-5.

Thanks!

**Comment by aleph1** [comment]
I think I have figured this out using Graphics4. Thanks.

**Comment by RobDangerous** [comment]
Aye, when g2 is not sufficient using g4 is the right approach. You can also use g2 as a nice code sample because it is itself implemented via g4.
