### ISSUE TITLE
Metal application, every second frame is black.

### ISSUE THREAD

**Issue by aleph1** [Kode/Kore#375]
I am having a strange behaviour when I run an application compiled to use Metal in that every other frame appears black. The same code application beautifully when compiled to use OpenGL.

I'm just testing out the code for creating per-vertex coloured buffers, so nothing out of the ordinary.

#include "pch.h"

#include <Kore/IO/FileReader.h>
#include <Kore/Graphics4/Graphics.h>
#include <Kore/Graphics4/PipelineState.h>
#include <Kore/Graphics4/Shader.h>
#include <Kore/System.h>
#include <stdlib.h>

using namespace Kore;

namespace {
	Graphics4::Shader* vertexShader;
	Graphics4::Shader* fragmentShader;
	Graphics4::PipelineState* pipeline;
	Graphics4::VertexBuffer* vertices;
	Graphics4::IndexBuffer* indices;
	Graphics4::ConstantLocation projectionLocation;

	Window* window;

	int width;
	int height;

	void update() {

		float halfWidth = width / 2;
		float halfHeight = height / 2;

		Graphics4::begin();
		Graphics4::clear(Graphics4::ClearColorFlag);

		// lock vertex buffer
		float* v = vertices->lock();
		// update position of triangle
		v[0] = halfWidth + random( -100.0, 100.0 ); // x1
		v[1] = halfHeight + random( -100.0, 100.0 ); // y1
		v[7] = halfWidth + random( -100.0, 100.0 ); // x1
		v[8] = halfHeight + random( -100.0, 100.0 ); // y1
		v[14] = halfWidth + random( -100.0, 100.0 ); // x1
		v[15] = halfHeight + random( -100.0, 100.0 ); // y1
		// unlock vertex buffer
		vertices->unlock();
		
		// 
		Graphics4::setPipeline(pipeline);
		Graphics4::setVertexBuffer(*vertices);
		Graphics4::setIndexBuffer(*indices);

		// set camera projection
		Graphics4::setMatrix( projectionLocation, mat4::orthogonalProjection(0.f, static_cast<float>(width), static_cast<float>(height), 0.f, 0.f, 1000.f));

		// draw vertices
		Graphics4::drawIndexedVertices();

		Graphics4::end();
		Graphics4::swapBuffers();
	}
}

int kore(int argc, char** argv) {

	width = 1440;
	height = 900;

	Kore::WindowOptions windowOptions;
	windowOptions.width = width;
	windowOptions.height = height;
	//windowOptions.windowFeatures = WindowFeatureBorderless;
	windowOptions.mode = Kore::WindowMode::WindowModeExclusiveFullscreen;

	Kore::System::init("Vie", width, height, &windowOptions);
	Kore::System::setCallback(update);

	FileReader vs("shader.vert");
	FileReader fs("shader.frag");
	vertexShader = new Graphics4::Shader(vs.readAll(), vs.size(), Graphics4::VertexShader);
	fragmentShader = new Graphics4::Shader(fs.readAll(), fs.size(), Graphics4::FragmentShader);

	//
	Graphics4::VertexStructure structure;
	structure.add("pos", Graphics4::Float3VertexData);
	structure.add("col", Graphics4::Float4VertexData);

	// create pipeline state
	pipeline = new Graphics4::PipelineState();
	pipeline->vertexShader = vertexShader;
	pipeline->fragmentShader = fragmentShader;
	pipeline->inputLayout[0] = &structure;
	pipeline->inputLayout[1] = nullptr;
	pipeline->compile();

	// store projection location
	projectionLocation = pipeline->getConstantLocation("projectionMatrix");

	// create vertex buffer
	vertices = new Graphics4::VertexBuffer(3, structure, Graphics4::Usage::DynamicUsage);
	// lock vertex buffer
	float* v = vertices->lock();
	// populate vertex buffer
	v[0] = -1.0; // x1
	v[1] = -1.0; // y1
	v[2] = 0.0; // z1
	v[3] = 1.0; // r1
	v[4] = 0.0; // g1
	v[5] = 0.0; // b1
	v[6] = 1.0; // a1
	v[7] = 1.0; // x1
	v[8] = -1.0; // y1
	v[9] = 0.0; // z1
	v[10] = 0.0; // r2
	v[11] = 1.0; // g2
	v[12] = 0.0; // b2
	v[13] = 1.0; // a2
	v[14] = -1.0; // x3
	v[15] = 1.0; // y3
	v[16] = 0.0; // z3
	v[17] = 0.0; // r3
	v[18] = 0.0; // g3
	v[19] = 1.0; // b3
	v[20] = 1.0; // a3
	// unlock vertex buffer
	vertices->unlock();

	// create index buffer
	indices = new Graphics4::IndexBuffer(3);
	// lock index buffer
	int* i = indices->lock();
	// populate index buffer
	i[0] = 0; i[1] = 1; i[2] = 2;
	// unlock index buffer
	indices->unlock();

	Kore::System::start();

	return 0;
}

**Comment by aleph1** [comment]
Also, when this same application uses metal if I mouse over the Apple menu so that the window title becomes visible then all content stops rendering. It only resumes rendering if I mouse off of the Apple menu. If it helps I can provide a screen recording of the issue.

**Comment by aleph1** [comment]
If this makes it easier I have uploaded the project that is causing the issue:

https://github.com/aleph1/KoreMetalTest

If I compile this using OpenGL everything runs fine. When using Metal the screen sometimes appears black, and in this case if I mouse up to the top of the screen so the Apple menu appears the rendering starts, but only every other frame is rendered (basically it looks like it is strobing). Other times the rendering starts at launch but there is still strobing.

Do metal vertices have to be passed to the GPU in a clockwise/counterclockwise fashion? Right now I am randomizing vertex position per update, so will test that out as well.

**Comment by melMass** [comment]
@aleph1 Please format and edit your answer/questions it's hard to read quickly

**Comment by aleph1** [comment]
This is no longer an issue with a newer version of Kinc.
