### ISSUE TITLE
Audio3 Channel usage.

### ISSUE THREAD

**Issue by aleph1** [Kode/Kore#379]
I am looking to programatically generate sounds (sine wave and filters) using Kore, and think the Audio3 createChannel approach seems to be the way to go, but I can't deduce how to use the function parameters, vec3 origin, and AudioCallback callback. If you can provide some guidance I would happily write a tutorial or create an example to add to the https://github.com/Kore-Samples repository on how to implement audio synthesis.

**Comment by RobDangerous** [comment]
You're looking at the wrong place, Audio3 is for 3D-Audio. Audio2 does exactly what you want and you can have a look at Audio1 for some sample code.

PS: In the future please use the forum at http://forum.kode.tech for asking questions.
