### ISSUE TITLE
Rust bindings potential issues when using bindgen

### ISSUE THREAD

**Issue by mundusnine** [Kode/Kore#389]
In reference to [this](http://forums.armory3d.org/t/rust-and-the-vision-of-armory/3146/22) I decided to test out how this could be done with kinc using [bindgen](https://github.com/rust-lang/rust-bindgen)

Notes from my tests: 
- While testing it out with Kore I had issues with the wrapper.h files where if display.h uses system.h but it is not yet  found by the compilation it just errors out saying it can't find it. Basically, orderring of the *.h includes in the wrapper.h impacts compilation like normal compilation(it's using clang to parse source files). I believe that even with good ordering it may still be an issue(see last point).

- While testing with Kinc, the KINC_FUNC def was not found and bindgen just errored out.

- Bindgen seems to prefer single-file headers. In my tests I tried with the [cute](https://github.com/RandyGaul/cute_headers) headers and generation went smoothly for most of the headers. Files that worked did not have includes.

**Comment by RobDangerous** [comment]
I do not intend to use an automatic binding generator so none of this is an issue.
