### ISSUE TITLE
Error in android-native

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/Kore#39]
C:\Dev\Projetos\Kha\Invasion\build\android-native-build\Invasion\app\src\main\jni\SDKs\Kha\Kore\Backends\OpenGL2\Sources\Kore\RenderTargetImpl.cpp

Error:(78, 31) error: 'GL_DEPTH24_STENCIL8' was not declared in this scope
Error:(89, 31) error: 'GL_DEPTH32F_STENCIL8' was not declared in this scope
Error:(102, 45) error: 'GL_DEPTH_STENCIL_ATTACHMENT' was not declared in this scope

**Comment by sh-dave** [comment]
I probably broke it, will take a look.

**Comment by sh-dave** [comment]
Fixed in #40. And thanks, i didn't even know there is an android-native target until today :sweat_smile:
