### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by pragma37** [Kode/Kore#419]
If I run `node Kinc/make` from the parent directory I get a message that says `kincfile not found.`
If I run `node make`  from the Kinc folder it builds a visual studio project but the project won't load. I get an error that says `The item "../Source/Shaders/g1.frag.glsl" already exists under the filter "".`
Every shader seems to be duplicated in `Kore.vcxproj`. 
If I manually delete the duplicated items the solution loads, but when I compile I get loads of linker errors.

**Comment by RobDangerous** [comment]
Are you trying to build Kinc by itself? Because that's not how it works, you build a project which uses Kinc like for example https://github.com/Kinc-Samples/Shader-Kinc

**Comment by pragma37** [comment]
Oops! You're right. Sorry.
That sample project compiled fine.
Thank you.
