### ISSUE TITLE
Error in Android-native with gradle

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/Kore#43]
In android-studio:

```
Gradle '<project name>' project refresh failed
Error:Cause: org.gradle.api.internal.ExtensibleDynamicObject
```

< project name > being the name of the project.

**Comment by RobDangerous** [comment]
Please tell me more about that, don't act like an error message box ;)

**Comment by RafaelOliveira** [comment]
sorry, the error is showing in the console after I open the project. I found the android-studio log, there is a big stack-trace.

```
2016-02-27 12:15:31,092 [  79089]   INFO - .project.GradleProjectResolver - Gradle project resolve error 
org.gradle.tooling.GradleConnectionException: Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.5-all.zip'.
```

this is the full log: http://hastebin.com/raw/ilimavocez

**Comment by RobDangerous** [comment]
Haven't seen this before. Was this your first try doing something with the android-native target? Do regular Android NDK projects work? "Gradle project resolve error" kinda sounds like your Android Studio installation is broken.

**Comment by RafaelOliveira** [comment]
No, I already compiled android-native projects many times. This happened after I upgrade Kha to the latest. Was working before. But I will reinstall android-studio.

**Comment by RobDangerous** [comment]
Oh, do some more tests before your reinstall. I merged Dave's monster pull request yesterday. Did you try a completely clean build aka deleting the build dir?

**Comment by RafaelOliveira** [comment]
yes, I'm deleting the build folder and the korefile.js. I will check more.

**Comment by x17head** [comment]
I was able to reproduce the error with my own code that is know to work with latest android-java.

**Comment by sh-dave** [comment]
fixed in https://github.com/KTXSoftware/koremake/pull/15
