### ISSUE TITLE
Unable to compile shaders on macOS

### ISSUE THREAD

**Issue by ghost** [Kode/Kore#435]
To reproduce the issue I just git cloned Kinc, added a source main.c and a kincfile, then ran "node Kinc/make" in the command line and the error that comes up is:

Compiling shader 1 of 10 (g1.frag).
Error: EACCES: permission denied, open '/g1.frag'

**Comment by ghost** [comment]
Also, I tried running "sudo node Kinc/make" and that compiled the shaders fine, but when I try and compile the Xcode project it says undefined reference to _kickstart, even though I provide a definition in main.c

**Comment by RobDangerous** [comment]
I can not reproduce any of that. Try to run the code from https://github.com/Kinc-Samples/Shader-Kinc and put it in a directory for which you have read and write access.
There doesn't seem to be an issue with Kinc here, so I'm closing this - if you need further assistance, please visit the forum at http://forum.kode.tech/.

**Comment by ghost** [comment]
So I tried cloning the sample (on the desktop) and everything worked fine, up until I modified kincfile.js then I get the same errors again. I'm not sure what the problem could possibly be if it's not an issue with Kinc.
