### ISSUE TITLE
iOS save path is not retained.

### ISSUE THREAD

**Issue by jurmerlo** [Kode/Kore#441]
When ```getSafePath``` in System.mm on iOS stores the save path it doesn't get retained. The path only returns correctly the first time ```kinc_internal_save_path``` gets called.

I fixed it in my local version by returning the path from ```getSafePath``` every time instead of storing it but I'm not sure if that is the best solution.

Did a quick test and seems like the issue is the same on MacOS.

**Comment by RobDangerous** [comment]
Today we learned an important English lesson. The save path is not a safe path.

PS: Thanks for figuring this out.

**Comment by RobDangerous** [comment]
Had a quick look and I'm fine with calling getSavePath every time. Would you like to send a pull request to get proper credit in the commit log?

**Comment by jurmerlo** [comment]
Haha English is not my native language. Get that stuff mixed up all the time. I'll create a pull request for it.

**Comment by RobDangerous** [comment]
Same for me, but it's what allowed me to make a fancy two-in-one pun. Looking forward to the pull request.
