### ISSUE TITLE
Android native build failed (Graphics::*)

### ISSUE THREAD

**Issue by zaynyatyi** [Kode/Kore#45]
Getting error while compiling android native app in android studio
/app/src/main/jni/Kha/Kore/Sources/Kore/Application.cpp
Error:(28, 17) error: too few arguments to function 'void Kore::Graphics::init(int, int, int)'
Information:(3) (Unknown) In file included
Error:(32, 20) error: too few arguments to function 'void Kore::Graphics::destroy(int)'
  Graphics::destroy();

**Comment by RobDangerous** [comment]
Oh, why is this closed?

**Comment by zaynyatyi** [comment]
i removed my build folder and rebuilt from scratch and it's gone.

**Comment by RobDangerous** [comment]
Ah, that happens, C++ compilers get confused sometimes. Android Studio should also have a clean build thing somewhere for such cases.
