### ISSUE TITLE
Dear ImGui sample attempts to call missing method

### ISSUE THREAD

**Issue by prime31** [Kode/Kore#455]
`kinc_g4_draw_indexed_vertices_from_to_from` does not seem to be available in the codebase that kincmake generates. This results in the error:

```
Undefined symbols for architecture x86_64:
  "_kinc_g4_draw_indexed_vertices_from_to_from", referenced from:
      ImGui_ImplG4_RenderDrawData(ImDrawData*) in imgui_impl_g4.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by RobDangerous** [comment]
Oh, I just haven't yet implemented that for all backends I think.

**Comment by prime31** [comment]
That’s what I figured. I saw it in there for GL I think or maybe DX.
