### ISSUE TITLE
[Feature Request] implement a way to override `main`

### ISSUE THREAD

**Issue by prime31** [Kode/Kore#457]
Something similar to Sokols NO_ENTRY as seen here: https://github.com/floooh/sokol/blob/master/sokol_app.h#L19

Basically, a way for an app to have its own `main` method that can call into kinc and have kinc fire off the normal platform run loop.

One such quick-and-dirty example used to get a test window up and running is this:

```c
void kinc_run(void (*value)()) {
	init_callback = value;
	@autoreleasepool {
		myapp = [MyApplication sharedApplication];
		[myapp performSelectorOnMainThread:@selector(run) withObject:nil waitUntilDone:YES];
	}
}
```

Then the run method calls the callback. In the callback is where the normal `kickstart` calls wouuld be made.
```c
- (void)run {
	@autoreleasepool {
		[self finishLaunching];
		[[NSRunningApplication currentApplication] activateWithOptions:(NSApplicationActivateAllWindows | NSApplicationActivateIgnoringOtherApps)];
		NSApp.activationPolicy = NSApplicationActivationPolicyRegular;

		hidManager = new Kore::HIDManager();
		addMenubar();

		init_callback();
	}
}
```

Note that `NSApp.activationPolicy = NSApplicationActivationPolicyRegular;` was added, which was required to get the window displaying.

**Comment by mundusnine** [comment]
Trying my luck here, but could this be added to kinc as it would make it easier to add wrappers to other languages then haxe.

**Comment by RobDangerous** [comment]
It's all Kinc here :)

**Comment by RobDangerous** [comment]
Heyho, all done for Windows, macOS (better than via the older pull request) and Linux.
