### ISSUE TITLE
kinc_init has a name parameter that isnt used

### ISSUE THREAD

**Issue by prime31** [Kode/Kore#458]
It seems the `kinc_window_options` has the window title already so the name parameter probably isnt needed.

**Comment by RobDangerous** [comment]
The name is used for more than just the window title - it's for example used for the save directory on desktop systems. The kinc_window_options title can override the name when the window title is supposed to be different to the name. I made that a little more consistent now by defaulting the window title to the name when it isn't set explicitly.
