### ISSUE TITLE
[Feature Request] 16-bit index buffer

### ISSUE THREAD

**Issue by BenjaminGu** [Kode/Kore#471]
I want to create a 16-bit index buffer.
But, I can't find it in Kinc.

**Comment by luboslenco** [comment]
https://github.com/Kode/Kinc/pull/479 is merged - I implemented it for OpenGL but it should be easy now to create a pull-request for any graphics api you need. 🙂

**Comment by BenjaminGu** [comment]
Thank you.  Currently, I'm only using OpenGL ES.
If I use DX11 or Metal later, I'll make a pull request for it.
