### ISSUE TITLE
GL_MAX_COLOR_ATTACHMENT ignored, causes errors on some OpenGL ES devices

### ISSUE THREAD

**Issue by AlexRamallo** [Kode/Kore#482]
The minimum value for GL_MAX_COLOR_ATTACHMENT is 8 in OpenGL, but 4 in OpenGL ES.

Commit 656cecda1c5d7a7c7f0c36f83ee03f2391c4e0fe seems to assume that the minimum is 8. That results in `GL_INVALID_ENUM` errors on two of my test devices. It also probably wouldn't do what it was originally meant to do on implementations with more than 8 attachments.

The fix could look something like this:
```
	GLint max_attachments = 0;
	glGetIntegerv(GL_MAX_COLOR_ATTACHMENTS, &max_attachments);

	for (int i = count; i < max_attachments; ++i) {
		glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0 + i, GL_TEXTURE_2D, 0, 0);
		glCheckErrors();
	}
```

However, when I tried that on my local repo, I got a build error saying GL_MAX_COLOR_ATTACHMENTS is undefined when trying to build for Android, and I'm not sure how to fix that. _(Hard-coding the value `0x8CDF` in its place seems to work on all my test devices though...)_

**Comment by luboslenco** [comment]
> Hard-coding the value 0x8CDF in its place seems to work on all my test devices

Defining it manually when necessary should be ok then:
https://github.com/Kode/Kinc/blob/master/Backends/Graphics4/OpenGL/Sources/Kore/OpenGL.cpp#L45

And maybe if `glGetIntegerv` ever fails, let `max_attachments` default to 4?
```c
GLint max_attachments = 4;
glGetIntegerv(GL_MAX_COLOR_ATTACHMENTS, &max_attachments);
```

**Comment by AlexRamallo** [comment]
I did some more digging and learned that `GL_MAX_COLOR_ATTACHMENTS` in the NDK is defined in the GLES3 headers, whereas the GLES2 headers define `GL_MAX_COLOR_ATTACHMENTS_EXT` instead, and they're all the same value. That seems to be the same as [the headers on the Khronos site](https://www.khronos.org/registry/OpenGL/index_es.php#headers2), so it's not a weird Android thing. But since they're all defined to the same value, your solution would be cleaner than a conditional.

Also, I'm not sure if calling `glGetIntegerv` in that function would be efficient since that value should never change. Maybe it should be called and cached somewhere else? Or it doesn't matter?

**Comment by luboslenco** [comment]
Sounds good! Yes, a nice place to cache the `glGetIntegerv` result could be along these lines in `kinc_g4_init`:
https://github.com/Kode/Kinc/blob/master/Backends/Graphics4/OpenGL/Sources/Kore/OpenGL.cpp#L178
