### ISSUE TITLE
[OS: Windows, Backend: Vulkan] SwapChain is not recreated when resizing the window.

### ISSUE THREAD

**Issue by Linuxydable** [Kode/Kore#483]
Hello,

OS: Windows
Backend: Vulkan

I my program crash when resizing, I have searched and it's maybe a problem with the SwapChain recreation with Vulkan.

**Comment by luboslenco** [comment]
Hey, this should be resolved now.

**Comment by Linuxydable** [comment]
Hello,

Thank you so much, I'm gonna close this issue.
