### ISSUE TITLE
OpenGL error code 1286 - Invalid Framebuffer

### ISSUE THREAD

**Issue by luboslenco** [Kode/Kore#49]
Tested using BlocksFromHeaven and OSX, OpenGL started to spit out error code 1286. Everything still appears to work fine, but it's problematic when debugging OpenGL code. Will have a look in coming days but if anyone is aware of this please report.

**Comment by sh-dave** [comment]
Hm, no errors on
- iMac(Late 2013)
- OS X El Capitan - 10.11.3
- NVIDIA GeForce GT 755M 1024 MB
- Kha: https://github.com/KTXSoftware/Kha/commit/ad6c560b99e06e74177f102a0204bf5573f06912

**Comment by luboslenco** [comment]
Getting interesting, as usual:) Thanks for testing.
GPU here: Intel Iris 5100

**Comment by luboslenco** [comment]
Latest BlocksFromHeaven-Kore is stuck printing error code 1286(at glClear()), it plays music but does not display anything.

Previous commit from Feb 9, 2016, f9fc07fa6e4f4c2e3bb71e98833516475a691352, works fine. What is worse, the error does not seem to be related to RenderTargetImpl changes.

**Comment by RobDangerous** [comment]
This is fixed, isn't it?

**Comment by luboslenco** [comment]
I still experienced it a few weeks back, it's probably GPU/OS specific and happens only once with no apparent harm done. Would not mind closing this - I seem to be the only one hitting this anyway.

**Comment by RobDangerous** [comment]
ok, will try myself on macOS tomorrow and close if I can't reproduce (and in that case I'll also send an angry mail to intel of course).

**Comment by RobDangerous** [comment]
No errors for me.

**Comment by nsinh008** [comment]
I have been facing this issue and am unable to resolve this. 
Can someone suggest if any solution was found please?

**Comment by RobDangerous** [comment]
macOS OpenGL is now spitting out errors regularly. Feel free to send a pull request, should be easy to resolve. I concentrate on the Metal target nowadays though because Apple's OpenGL support is severely outdated.
