### ISSUE TITLE
Alt key stuck after alt+tab on Windows

### ISSUE THREAD

**Issue by luboslenco** [Kode/Kore#525]
- Tested on https://github.com/Kinc-Samples/Shader-Kinc + latest Kinc
- `node Kinc/make windows -g direct3d11` and run
- Press alt+tab to focus out of the window
- Press alt+tab again to focus back to the window
- Pressing enter key alone now toggles the fullscreen mode (via https://github.com/Kode/Kinc/commit/8f27cc53857999428e1a2fe0e74705e9e023132c)

**Comment by RobDangerous** [comment]
Hey, it's not my fault when you don't clean your keyboard.
