### ISSUE TITLE
Detect eraser pen input rather than treating it as mouse input

### ISSUE THREAD

**Issue by 5Mixer** [Kode/Kore#551]
Currently only the 'pen' side of tablet pen input is detected. The eraser side is treated as mouse input. Reusing the existing Pen api as much as possible makes sense - the same events with `x`, `y`, and `pressure` are relevant. Alternative methods for the eraser could be created, or perhaps an additional `eraser` boolean could be passed.

Relevant Kha issue: https://github.com/Kode/Kha/issues/1240

**Comment by RobDangerous** [comment]
There's a merged pull-request. There's a closed Kha-issue. That probably means we're done here.
