### ISSUE TITLE
linking error: extern void* with -dynlib

### ISSUE THREAD

**Issue by ustance** [Kode/Kore#565]
**Describe the bug**
When using a Kinc dll on Windows with clang or msvc any extern void* callbacks can't be found.

**Execution Environment:**
- Host system: Windows 10 x64
- Target system: Windows 10 x64
- IDE and/or compiler used: clang, msvc
- Application output (if it runs): LNK2019

**Comment by RobDangerous** [comment]
What void* variables?

**Comment by ustance** [comment]
every extern void* callback in the input folder (mouse, gamepad, etc.). I looked briefly, I don't think there is more void* out there

**Comment by RobDangerous** [comment]
Those are not void*. Those are function pointers. And I can successfully get those via GetProcAddress. What was the procedure to reproduce that problem using C?

**Comment by RobDangerous** [comment]
Looks like it's actually working, just make sure to define KORE_WINDOWS and KINC_DYNAMIC.
