### ISSUE TITLE
Emscripten compilation fails because of kickstart

### ISSUE THREAD

**Issue by mundusnine** [Kode/Kore#567]
**Describe the bug**
Emsdk compilation doesn't work with --dynlib or [plainly](https://github.com/Kode-Community/Kinc/runs/1231791336?check_suite_focus=true#step:7:120) because [this](https://github.com/Kode-Community/Kinc/runs/1231707295?check_suite_focus=true#step:7:120)

**To Reproduce**
1. Compile for html5

**Expected behavior**
Compiles

**Execution Environment:**
- Ubuntu-latest github
- html5
- emscripten
- most recent
- See link linked before

**Comment by RobDangerous** [comment]
It's not supposed to work with --dynlib and html5 and compiling plainly of course needs a kickstart function.
