### ISSUE TITLE
emscripten error on image uploading to webgl.

### ISSUE THREAD

**Issue by Paolo-Oliverio** [Kode/Kore#569]
WebGL: INVALID_VALUE: texImage2D: invalid internalformat
_glTexImage2D @ kore.js:1
kore.html:1 GL Error 1281 ......\thirdparty\kinc\Backends\Graphics4\OpenGL\Sources\Kore\TextureImpl.c 340

I just tried png 8bit , 32 bit and jpg all gives the same error.
Tested both pow2 and nonpow2.

https://github.com/Kinc-Samples/Texture-Kinc has the same exact behaviour.

-  Emcc 2.0.5 clang version 12.0.0  x86_64-pc-windows-msvc 
- Tested on Microsoft Edge 86.0.622.43 64bit and Chrome 86.0.4240.75 64bit
- Kinc master.

**Comment by Paolo-Oliverio** [comment]
if I set in opengl textureimpl.c convertInternalFormat default to GL_RGBA instead of GL_RGBA8 textures get rendered correctly

**Comment by RobDangerous** [comment]
You fixed it yourself.
