### ISSUE TITLE
emscripten html5 bad performance on chrome android.

### ISSUE THREAD

**Issue by Paolo-Oliverio** [Kode/Kore#570]
kinc html5 on android features very poor fps especially when not touching the screen.
moving a finger on the screen makes fps rise up to 60fps with simple clear screen still the performances are really bad when rendering somehting using graphic4.
Tested on multiple android phones.
The same html5 on pc apparently doesn't suffer this issue maxing out the fps to the monitor refresh.

**Comment by RobDangerous** [comment]
Checked the Texture-sample on Chrome Android and all was fine. Hopefully Google fixed something.
