### ISSUE TITLE
.o files polluting source directories when compiling html5/emscripten

### ISSUE THREAD

**Issue by Paolo-Oliverio** [Kode/Kore#572]
expect to see .o files better organized and not generated next the souce code as they also shows up in some ide.

**Comment by RobDangerous** [comment]
Oh hey, this is fixed.

**Comment by Paolo-Oliverio** [comment]
I have tried it and it works, thanks.

Il lun 9 nov 2020, 18:03 Robert Konrad <notifications@github.com> ha
scritto:
