### ISSUE TITLE
Index buffer lacking features.

### ISSUE THREAD

**Issue by Paolo-Oliverio** [Kode/Kore#582]
things missing:

proper 16bit / 32bit difference without dual allocation and conversion on copy.
maybe it can return void* as 32bit is not supported everywhere  and so the use of the right firmat should be truly deliberated so to justify the additional cast.

sub resource lock and unlock especially in the case of dynamic buffer one may preallocate a large buffer with this addition is more pay for what you use now you just pay for the worse case.

lack of static and dynamic distinction so now everything is static lowering performances in case of frequent updates.

could be done in steps initially just in kinc with kore following in a second step.

**Comment by RobDangerous** [comment]
All fixed.
