### ISSUE TITLE
Amazon FireTV Remote Input

### ISSUE THREAD

**Issue by sh-dave** [Kode/Kore#59]
I'm adding support for the FireTv remote (gamepad support will probably come later, don't have acess to one yet) and have a question.

The remote (and some variants of the amazon gamepad) feature 'MENU', REWIND', 'PLAY / PAUSE', 'FAST FORWARD' buttons. As my usecase is to treat them like a gamepad, should i only forward them to kha.Input.GamePad.button or create new special keys in kha.input.Key as well (kha.input.Key.REWIND, ...) while i'm on it?

**Comment by RobDangerous** [comment]
I think special keys for that would indeed make sense.

**Comment by RobDangerous** [comment]
Hmmm, I suppose the issue died of old age.
