### ISSUE TITLE
[linux-native] Cut/copy text not available after closing Kha app

### ISSUE THREAD

**Issue by Sanva** [Kode/Kore#602]
**Describe the bug**
If you cut/copy text from a Kha app it can be pasted into other apps. But after closing the Kha app the text is no longer available.

**To Reproduce**
1. Cut or copy text in a Kha app — it will be ready to be pasted in any other system app.
2. Close the Kha app — you can't paste the text anymore.

**Expected behavior**
Clipboard text should be available after closing the app, just like with *regular* apps.

**Execution Environment:**
- Host system (where you compile your code): Linux Mint 19.2 (Linux 4.15.0-132-generic x86_64)
- Target system (where you run your code): Linux Mint 19.2 (Linux 4.15.0-132-generic x86_64)
- IDE and/or compiler used: Not sure, chosen by khamake/kincmake.
- Kha/Kinc revision/build output: Kha in master, with corresponding Kinc revision — I only use Kinc from Kha, but knowing a little about the implementations, looks like a bug in Kinc. Not sure if would be more desirable to open the bug there.
- Application output (if it runs):

```
Starting Kinc
Starting application
```

**Additional context**
I'm a Linux user from some time now, and this bug seems a bit curious to me, because if I remember correctly, at some point more than a decade ago this was the *regular* behavior of some (if not all) Linux apps. Also, this is the intended behavior (as far as I know, which is little) when *copying* text by selecting it: You can paste that kind of *copied* text only if the source app remains open.

**Comment by RobDangerous** [comment]
Looks like this is normal behavior for X applications (see #603) but if you ever find out more about it, I'll be all ear.
