### ISSUE TITLE
AGDK Usage

### ISSUE THREAD

**Issue by lublak** [Kode/Kore#634]
**Is your feature request related to a problem? Please describe.**

Currently, there is no problem with kinc, only an idea to solve possible compatibility problems or to have easier maintenance.

**Describe the solution you'd like**

https://developer.android.com/games/agdk
Google releases the Android Game Development Kit to work with C/C++.
It supports standard methods for running games on an Android device, including input capabilities and backwards compatability.

**Describe alternatives you've considered**

That it is only an idea that actually only means more work, but I would like to make a note of it. The alternative, of course, is to leave it as it is.

**Additional context**

The download for the libraries:
https://developer.android.com/games/agdk/download#agdk-libraries

**Comment by RobDangerous** [comment]
Yes, already had a look - precompiled libs without sources, incompatible license... as of now it's sadly just one big horror show.

**Comment by lublak** [comment]
@RobDangerous oh you are faster xD I just saw it and thought heyyy this might be something for kinc, make a note of that for now.
Of course, that's a really stupid thing again.
The licence will probably not change.
And thanks for the answer :)

**Comment by RobDangerous** [comment]
And thank you for the suggestion even though I didn't follow it this time.
