### ISSUE TITLE
software rendering graphics api

### ISSUE THREAD

**Issue by lublak** [Kode/Kore#670]
**Is your feature request related to a problem? Please describe.**

There are certain devices that do not support gpu rendering.
It would be interesting to offer a fallback to software rendering (g2).

**Describe the solution you'd like**

Another backend based on gdi+ (win), quartz 2d (mac) and cairo (linux).

**Describe alternatives you've considered**

I don't know of any alternative at the moment.

**Additional context**

The idea came from using haxeui kha for desktop development.
Only the g2 interface is used. Shader support can be problematic in the implementation.

**Comment by RobDangerous** [comment]
g1 is the API for software-rendering. There's also an implementation of g2 on top of that (graphics_soft.c ). There's currently only an implementation on top of g4 but feel free to send pull-requests to run it on something else (I don't plan to work on that myself though).
