### ISSUE TITLE
Support more controller types and amounts

### ISSUE THREAD

**Issue by mundusnine** [Kode/Kore#707]
**Is your feature request related to a problem? Please describe.**
Someone in the Kode community wants more Inputs for couche coop games. His name starts with `Do` and finishes with `us`, not that this matters.

**Describe the solution you'd like**
On windows, to support generic gamepads and dualshock4 we could use [this](https://github.com/MysteriousJ/Joystick-Input-Examples/blob/main/src/combined.cpp)
In the same vein, on windows we could support nintendo switch controllers using a [HID api](https://github.com/MysteriousJ/Joystick-Input-Examples#windows-specialized-io) and [data](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering) reverse engineered
On linux, this is easy, by using evdev.

**Comment by RobDangerous** [comment]
The license of that Joystick-Input-Example thing is incompatible. If you know how evdev makes those things easy, please send a pull-request.

**Comment by RobDangerous** [comment]
Also isn't this all wrong? Generic gamepads and Dual Shock 4 are already supported on Windows and what I once talked about with Dom was not support for more controller types but merely automatic button mapping to make all controllers work the same. Closing this.
