### ISSUE TITLE
Trying to use `krafix_compile`in a thread crashes on mac os

### ISSUE THREAD

**Issue by tcdude** [Kode/Kore#772]
**Describe the bug**
I call `krafix_compile` from a thread, triggered by an event, which crashes the app when running it on mac os. 

**To Reproduce**
I made a small repo to reproduce the crash [here](https://github.com/tcdude/mackrafixrepro)

**Expected behavior**
I tested the same on LInux and Windows where the same works with no crash.

**Screenshots**
<img width="1421" alt="Screenshot 2023-02-24 at 00 43 32" src="https://user-images.githubusercontent.com/13047632/221056655-4af129da-a555-42ec-993d-e5cacccc6dc2.png">

**Execution Environment:**
- Host system (where you compile your code): macOS 13.2.1 (x64)
- Target system (where you run your code): same
- IDE and/or compiler used: Xcode Version 14.2 (14C18)
- Kinc revision: 980011d9
- Kinc build output: [See this](https://github.com/tcdude/mackrafixrepro/blob/main/build_log.txt)
- Application output (if it runs): N/A

**Additional context**
It works as expected when `krink_compile` is called on the main thread.

**Comment by RobDangerous** [comment]
Fixed by 03d99684b.
