### ISSUE TITLE
[Vulkan] Swapchain issues

### ISSUE THREAD

**Issue by Apprentice-Alchemist** [Kode/Kore#783]
**Describe the bug**
- VK_ERROR_SURFACE_LOST_KHR is not handled properly (mainly affects android)
- VK_SUBOPTIMAL_KHR (and VK_ERROR_OUT_OF_DATE_KHR) are not handled properly

**To Reproduce**
- Run Kinc app on Android, minimise it.
- Run Kinc app on Linux, resize the window and hope the driver complains.

**Expected behavior**
Minimising or resizing doesn't crash the app.

**Execution Environment:**
- Host system (where you compile your code): Linux
- Target system (where you run your code): Android and Linux
- IDE and/or compiler used:
- Kinc revision:
- Kinc build output:
- Application output (if it runs):

**Comment by RobDangerous** [comment]
That's now all fixed, right?

**Comment by RobDangerous** [comment]
Probably.
