### ISSUE TITLE
Linux - rootunit [ multiple definition of ] error

### ISSUE THREAD

**Issue by Onek8** [Kode/Kore#788]
**Describe the bug**
Running ../Kinc/make --run on sample project 01_triangle causes an initial error in
/home/onek8/Downloads/Kinc-Samples-main/01_triangle/Sources/main.c|94|error: too few arguments to function ‘kinc_g4_index_buffer_lock’|
/home/onek8/Downloads/Kinc-Samples-main/Kinc/Sources/kinc/graphics4/indexbuffer.h|52|note: declared here|
Then, passing the additional parameters I get the list of rootunit -> multiple definitions errors.

**Screenshots**
![Screenshot 2023-04-11 23:46:48](https://user-images.githubusercontent.com/20072039/231297732-d23ef230-cc26-447b-be4a-492cb7e94e8a.png)

**Execution Environment:**
Running on ubuntu 22.10
Latest kink+tools from 1 hour ago
Testing also with codeblocks project file + GNU GCC
Kode/Kinc + Armory Kinc

**Additional context**
The issue was initially found targeting Linux C hashlink from armory 3d and further confirmed with the 01_triangle sample file. I made an attempt of trying to understand the changes here https://github.com/Kode/Kinc/commit/8d3ffebab01907b1e58020a2a706d07582a2eb0a before making the report I would have preferred to find a fix. It is to note this only effects Linux users, atleast ubuntu in my case as the Armory windows users reported successful compilation with the armory kinc version.

**Comment by RobDangerous** [comment]
That's as expected, I haven't made those samples compile yet, I just copied them in to work on them later.
Just have a look at any of the working samples in the repo instead (everything that doesn't start with a number, also see https://github.com/Kode/Kinc-Samples/actions). And the index-buffer-API was changed for all targets, if Armory only has a problem on Linux, that's probably unrelated. The commit you point to is also unrelated to the index-buffer-changes. upates.md always lists all breaking changes like that and in that case even includes instructions on what to do.
