### ISSUE TITLE
D3D12 crash when hiding/showing window multiple times

### ISSUE THREAD

**Issue by RblSb** [Kode/Kore#822]
![20231018_024717](https://github.com/Kode/Kha/assets/8753432/100ccb3c-9801-400f-a403-a584f8a6ca46)

**Comment by RobDangerous** [comment]
Let's not hide Kinc issues in the Kha repo.

**Comment by RobDangerous** [comment]
Hopefully related to #810 which so far proved tricky.

**Comment by RobDangerous** [comment]
It was not related to #810 unfortunately. And Felix's fix is not yet good enough - it crashes with the repro from #810. And very latest info from http80 - keeping the window minimized also causes the crash.

**Comment by RobDangerous** [comment]
Ah, only crashes for http80 once he un-minimizes actually.

**Comment by mikaib** [comment]
Hey! Just wondering, has this been fixed in any of the commits or is it still an ongoing issue?

**Comment by RobDangerous** [comment]
The issue is still open aka it is still ongoing.

**Comment by RobDangerous** [comment]
Explanation going into #829 in a moment...
