### ISSUE TITLE
TextureFormat RGBA32 isn't working with compute.

### ISSUE THREAD

**Issue by e2002e** [Kode/Kore#855]
**Describe the bug**
RGBA32 images that are passed through compute shader are rendered black while an RGBA64 image will have data.

**To Reproduce**
Compile and run the sample https://github.com/e2002e/ComputeShader

**Expected behavior**
The window should display some patterns from the compute shader.

**Execution Environment:**
Ubuntu 23
OpenGL
Kinc branch main

**Comment by RobDangerous** [comment]
Priority is automatically lowered when you don't use the issue template by the way.

**Comment by e2002e** [comment]
I kind of used it.
Just skipped a section maybe. Anyway with the fix you did for the compute shaders I have a lot of work so take your time !
