### ISSUE TITLE
"Hidden" error when reaching MAX_THREADS

### ISSUE THREAD

**Issue by Alwe** [Kode/Kore#9]
(Backends/Windows/Sources/Kore/Thread.cpp)

Calling Kore::createAndRunThread while the thread limit is already reached leads to hard to debug errors. (Different breaking points for 32/64 bit Debug/Release at at first glance unrelated places.)

The issue is that the thread index is increased without regard to MAX_THREADS. A check and error message would be nice.
Furthermore it is not clear to us how one should free a thread. The index doesn't seem to be decreased anywhere.

**Comment by RobDangerous** [comment]
Sorry, will fix, only ever used it for one or two additional threads which are never destroyed (if you're working on Exercise11 that's probably the best strategy though).
