### ISSUE TITLE
Accessing unused texture unit

### ISSUE THREAD

**Issue by AoE-Maniac** [Kode/Kore#90]
If a texture unit tex is defined but not accessed in the shader, Graphics::setTextureAddressing(tex, U, Repeat); fails.

**Comment by RobDangerous** [comment]
I fixed a bunch of stuff like this but not sure about this one in particular. Was that D3D9?

**Comment by AoE-Maniac** [comment]
Works in D3D9 and OGL, only D3D11 fails:
D3D11 CORRUPTION: ID3D11DeviceContext::PSSetSamplers: First parameter out of range. [ MISCELLANEOUS CORRUPTION #13: CORRUPTED_PARAMETER1]

As an testcase you can check out https://github.com/AoE-Maniac/MultiplayerExample and change line 11 in Sources\Shaders\meshes.frag.glsl to
	gl_FragColor = vec4(((vec3(1, 0, 0) * 0.67 + max(dot(vec3(0.6, 0, 0.8), normal), 0.0) * 0.34).xyz), 1);
